### PR TITLE
Fix AssetManager Path issue #14

### LINKED ISSUE #14: [TextureAtlas] Unable to find texture from subdirectory
Hello

Let's say my asset folder is there:

AssetManager = new AssetManager(new FileAssetResolver("data"));

i have my atlas there:

data/textures/myatlas.atlas

atlas reference the texture like that:
sprites.png

sprites.png is in data/textures/sprites.png

But the loader will check here:

data/sprites.png  so it's wrong

### PR DESCRIPTION
**Pull request by RUSshy**
Fix #14

### CODE REVIEW

**Comment by rds1983** [comment]
Great work, @RUSshy. Thanks!
Right now, my head isn't working properly. Tomorrow I'll evaluate your changes.

**Comment by rds1983** [comment]
Hey @RUSshy.
Can I ask you about two things:
1.  Revert you changes to BitmapFontExtensions.cs and TextureAtlasExtension.cs. And apply it to loaders instead(BitmapFontLoader and TextureAtlasLoader).
2. Squash all your commits into one. It could be done following way:
  1. git rebase -i [id_of_commit_before_your changes].
  2. In the text editor only first commit should be 'pick', while rest should be 's', so it should look like:
    pick aaaaa First commit
    s bbbb Second commit
    s ccccc Third commit
    s ddddd Fourth commit
  3. In the second text editor keep only one commit message.
  4. After the succesful rebase: git push origin patch-1 --force

Thanks!

**Comment by rds1983** [comment]
Nevermind. I figured out how to fix #14 without patching every loader. Thanks again for the work.

**Comment by RUSshy** [comment]
Hey, sorry im not good with git i did it from the website :P

**Comment by rds1983** [comment]
There's nothing to be sorry about. Anyway I figured out more general fix for #14. I made it so IAssetLoader works with AssetLoaderContext, which wraps AssetManager and adds base folder path: https://github.com/rds1983/Myra/commit/98a760e4616460a8b1ad9d2a7bf290d185952267

**Pull request closed without merging**
